### ISSUE TITLE
尝试升级judge0的语言版本

### ISSUE THREAD

**Issue by sparklyi** [STUOJ/STUOJ#65]

**Comment by ArtdragonXoX** [comment]
@sparklyi 请问是想问什么

**Comment by HEX9CF** [comment]
不太明白C是？

**Comment by sparklyi** [comment]
> @sparklyi 请问是想问什么

欸我靠 怎么发出去了 我想请教下你们有尝试使用dockerfile更新gcc版本吗

**Comment by sparklyi** [comment]
> 不太明白C是？

不好意思 刚才好像按到快捷键了

**Comment by ArtdragonXoX** [comment]
> > @sparklyi 请问是想问什么
> 
> 欸我靠 怎么发出去了 我想请教下你们有尝试使用dockerfile更新gcc版本吗

我在我的[yuki-image](https://github.com/ArtdragonXoX/yuki-image)中的dockerfile用了gcc
其中使用了RUN apk add --no-cache g++来安装 GCC
你可以参考一下

**Comment by ArtdragonXoX** [comment]
> > > > @sparklyi 请问是想问什么
> > > 
> > > 
> > > 欸我靠 怎么发出去了 我想请教下你们有尝试使用dockerfile更新gcc版本吗
> > 
> > 
> > 我在我的[yuki-image](https://github.com/ArtdragonXoX/yuki-image)中的dockerfile用了gcc 其中使用了RUN apk add --no-cache g++来安装 GCC 你可以参考一下
> 
> 我试试 我搞了几天了 一直更新不了judge0的c++， java py go我都更新了 就是c++难搞：）

我们还没尝试过更新judge0中的沙箱环境，不过我认为先使用
```
RUN apk update --no-cache
```
来更新软件包索引再安装GCC可能会是新一些的版本？

**Comment by sparklyi** [comment]
> > > > > @sparklyi 请问是想问什么
> > > > 
> > > > 
> > > > 欸我靠 怎么发出去了 我想请教下你们有尝试使用dockerfile更新gcc版本吗
> > > 
> > > 
> > > 我在我的[yuki-image](https://github.com/ArtdragonXoX/yuki-image)中的dockerfile用了gcc 其中使用了RUN apk add --no-cache g++来安装 GCC 你可以参考一下
> > 
> > 
> > 我试试 我搞了几天了 一直更新不了judge0的c++， java py go我都更新了 就是c++难搞：）
> 
> 我们还没尝试过更新judge0中的沙箱环境，不过我认为先使用
> 
> ```
> RUN apk update --no-cache
> ```
> 
> 来更新软件包索引再安装GCC可能会是新一些的版本？

好的谢谢，我先尝试下，我更新版本是参考的[这个模板](https://gitlab.com/edgar-group/judge0/-/tree/master?ref_type=heads)

**Comment by ArtdragonXoX** [comment]
> > > > > > @sparklyi 请问是想问什么
> > > > > 
> > > > > 
> > > > > 欸我靠 怎么发出去了 我想请教下你们有尝试使用dockerfile更新gcc版本吗
> > > > 
> > > > 
> > > > 我在我的[yuki-image](https://github.com/ArtdragonXoX/yuki-image)中的dockerfile用了gcc 其中使用了RUN apk add --no-cache g++来安装 GCC 你可以参考一下
> > > 
> > > 
> > > 我试试 我搞了几天了 一直更新不了judge0的c++， java py go我都更新了 就是c++难搞：）
> > 
> > 
> > 我们还没尝试过更新judge0中的沙箱环境，不过我认为先使用
> > ```
> > RUN apk update --no-cache
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 来更新软件包索引再安装GCC可能会是新一些的版本？
> 
> 好的谢谢，我先尝试下，我更新版本是参考的[这个模板](https://gitlab.com/edgar-group/judge0/-/tree/master?ref_type=heads)

祝你成功，有什么新进展欢迎回来继续讨论。

**Comment by sparklyi** [comment]
> > > > > > > @sparklyi 请问是想问什么
> > > > > > 
> > > > > > 
> > > > > > 欸我靠 怎么发出去了 我想请教下你们有尝试使用dockerfile更新gcc版本吗
> > > > > 
> > > > > 
> > > > > 我在我的[yuki-image](https://github.com/ArtdragonXoX/yuki-image)中的dockerfile用了gcc 其中使用了RUN apk add --no-cache g++来安装 GCC 你可以参考一下
> > > > 
> > > > 
> > > > 我试试 我搞了几天了 一直更新不了judge0的c++， java py go我都更新了 就是c++难搞：）
> > > 
> > > 
> > > 我们还没尝试过更新judge0中的沙箱环境，不过我认为先使用
> > > ```
> > > RUN apk update --no-cache
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 来更新软件包索引再安装GCC可能会是新一些的版本？
> > 
> > 
> > 好的谢谢，我先尝试下，我更新版本是参考的[这个模板](https://gitlab.com/edgar-group/judge0/-/tree/master?ref_type=heads)
> 
> 祝你成功，有什么新进展欢迎回来继续讨论。

你好 我发现`judge0`是基于`debian10`的，此版本可以下载的gcc知道8或9版本， 我尝试将`gcc13.2.0`容器复制到`judge0`镜像中貌似成功了，但缺少了`glibc2.3+`的依赖（后续我会再试试）； 也试了下直接编译`gcc`源码 但时间太长没有等到完成，如果你们后续有升级版本计划，希望对你们有帮助

**Comment by ArtdragonXoX** [comment]
> > > > > > > > @sparklyi 请问是想问什么
> > > > > > > 
> > > > > > > 
> > > > > > > 欸我靠 怎么发出去了 我想请教下你们有尝试使用dockerfile更新gcc版本吗
> > > > > > 
> > > > > > 
> > > > > > 我在我的[yuki-image](https://github.com/ArtdragonXoX/yuki-image)中的dockerfile用了gcc 其中使用了RUN apk add --no-cache g++来安装 GCC 你可以参考一下
> > > > > 
> > > > > 
> > > > > 我试试 我搞了几天了 一直更新不了judge0的c++， java py go我都更新了 就是c++难搞：）
> > > > 
> > > > 
> > > > 我们还没尝试过更新judge0中的沙箱环境，不过我认为先使用
> > > > ```
> > > > RUN apk update --no-cache
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 来更新软件包索引再安装GCC可能会是新一些的版本？
> > > 
> > > 
> > > 好的谢谢，我先尝试下，我更新版本是参考的[这个模板](https://gitlab.com/edgar-group/judge0/-/tree/master?ref_type=heads)
> > 
> > 
> > 祝你成功，有什么新进展欢迎回来继续讨论。
> 
> 你好 我发现`judge0`是基于`debian10`的，此版本可以下载的gcc知道8或9版本， 我尝试将`gcc13.2.0`容器复制到`judge0`镜像中貌似成功了，但缺少了`glibc2.3+`的依赖（后续我会再试试）； 也试了下直接编译`gcc`源码 但时间太长没有等到完成，如果你们后续有升级版本计划，希望对你们有帮助

谢谢你提供的宝贵经验，如果后续我们有升级的计划以及进展也会在此讨论。
